INSERT INTO chatbot (queries, replies) VALUES
  ('Hello', 'Hi there! How can I assist you?'),
  ('How are you?', 'I am doing well. Thanks for asking!'),
  ('What is your name?', 'My name is ChatBot. Nice to meet you!'),
  ('What is the weather today?', 'The weather is sunny and warm.'),
  ('Tell me a joke', 'Why don''t scientists trust atoms? Because they make up everything!'),
  ('Who is the CEO of Apple?', 'Tim Cook is the CEO of Apple.'),
  ('What is the capital of France?', 'The capital of France is Paris.'),
  ('How can I contact customer support?', 'You can contact customer support by calling our toll-free number: 1-800-123-4567.'),
  ('What are your working hours?', 'Our working hours are from 9 AM to 5 PM, Monday to Friday.'),
  ('Can I return a product?', 'Yes, you can return a product within 30 days of purchase. Please check our return policy for more details.'),
  ('Where can I find the user manual?', 'The user manual is available for download on our website. You can find it in the "Support" section.'),
  ('What payment methods do you accept?', 'We accept major credit cards, PayPal, and bank transfers.'),
  ('How long does shipping usually take?', 'Shipping usually takes 3-5 business days, depending on your location.'),
  ('Do you offer international shipping?', 'Yes, we offer international shipping to select countries. Please check our shipping policy for more information.'),
  ('What is your refund policy?', 'Our refund policy allows for refunds within 14 days of purchase. Please refer to our refund policy for complete details.'),
  ('Can I track my order?', 'Yes, you can track your order by entering your tracking number on our website.'),
  ('Do you have a mobile app?', 'Yes, we have a mobile app available for both iOS and Android devices.'),
  ('What are your best-selling products?', 'Our best-selling products include smartphones, laptops, and smartwatches.'),
  ('Can I apply for a job at your company?', 'Yes, you can view and apply for job openings on our careers page.'),
  ('How do I reset my password?', 'To reset your password, click on the "Forgot Password" link on the login page and follow the instructions.');
